name: "Matomo license existence checker"
description: Checks for LICENSE file existence and license key in plugin.json
author: Gary-H9
branding:
  icon: 'file-text'
  color: 'white'

runs:
  using: "docker"
  image: "Dockerfile"
